import { MARKETPLACE_PATTERN_CONTENT } from "@/lib/marketplace-pattern-content";
import { learnImage } from "@/lib/project-images";
import { projectImage } from "@/lib/project-images";
import type { MarketplaceListing } from "@/lib/schemas/marketplace";

const now = new Date().toISOString();

export const FEATURED_MARKETPLACE_LISTING_ID = "mp-cozy-granny-square-hoodie";

export const MARKETPLACE_SEED_LISTINGS: MarketplaceListing[] = [
  {
    id: "mp-dachshund-plushie",
    designerId: "designer-maya",
    designerName: "Maya Chen",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-1.svg",
    title: "Longbody Dachshund Amigurumi",
    description:
      "A low-sew dachshund plushie with floppy ears, embroidered nose, and a cream snout accent. Perfect gift for dog lovers.",
    aiDescription:
      "Meet your new best friend — a charming long-bodied dachshund worked entirely in the round. This pattern uses minimal seaming with clever color changes for the snout and paws. Intermediate makers will love the shaping techniques for the elongated body.",
    previewText:
      "Magic ring start · 38 rounds · 4.0 mm hook · Bernat Velvet worsted · Safety eyes · ~6 hours",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-dachshund-plushie"],
    priceCents: 599,
    skillLevel: "intermediate",
    projectType: "amigurumi",
    yarnWeight: "worsted",
    hookSize: "4.0 mm (G-6)",
    thumbnailUrl: projectImage.dachshund,
    tags: ["amigurumi", "dog", "plushie", "gift"],
    downloads: 1247,
    rating: 4.9,
    ratingCount: 312,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Longbody Dachshund Amigurumi",
        description: "A low-sew dachshund plushie with floppy ears.",
      },
      {
        language: "es",
        languageLabel: "Español",
        title: "Amigurumi Dachshund de Cuerpo Largo",
        description: "Un peluche dachshund de pocas costuras con orejas caídas.",
      },
      {
        language: "fr",
        languageLabel: "Français",
        title: "Amigurumi Teckel Long",
        description: "Une peluche teckel à coutures minimales avec oreilles tombantes.",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mp-sunflower-tote",
    designerId: "designer-rosa",
    designerName: "Rosa Martinez",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-2.svg",
    title: "Sunflower Market Tote",
    description:
      "A cheerful sunflower bag with a sturdy base and lined interior option. Great for farmers market runs.",
    aiDescription:
      "Carry summer everywhere with this bold sunflower tote. The pattern includes a flat bottom construction, 12-petal flower motif, and optional fabric lining instructions for extra durability.",
    previewText:
      "Flat bottom tote · 34 rounds flower panel · 5.0 mm hook · ~8 hours · Lining optional",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-sunflower-tote"],
    priceCents: 799,
    skillLevel: "intermediate",
    projectType: "bag",
    yarnWeight: "worsted",
    hookSize: "5.0 mm (H-8)",
    thumbnailUrl: projectImage.sunflower,
    tags: ["bag", "sunflower", "market", "summer"],
    downloads: 892,
    rating: 4.8,
    ratingCount: 198,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Sunflower Market Tote",
        description: "A cheerful sunflower bag with sturdy base.",
      },
      {
        language: "de",
        languageLabel: "Deutsch",
        title: "Sonnenblumen-Markttasche",
        description: "Eine fröhliche Sonnenblumentasche mit stabilem Boden.",
      },
      {
        language: "pt",
        languageLabel: "Português",
        title: "Bolsa Girassol de Mercado",
        description: "Uma bolsa alegre de girassol com base resistente.",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mp-granny-throw",
    designerId: "designer-elena",
    designerName: "Elena Wright",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-4.svg",
    title: "Classic Granny Square Throw",
    description:
      "A timeless granny square blanket with a modern color palette. Includes join-as-you-go method.",
    aiDescription:
      "Build cozy one square at a time. This throw pattern walks beginners through classic granny squares, color planning, and a seamless join-as-you-go technique — no endless weaving ends.",
    previewText:
      "20 squares · Join-as-you-go · 5.5 mm hook · Aran weight · Beginner friendly",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-granny-throw"],
    priceCents: 499,
    skillLevel: "beginner",
    projectType: "blanket",
    yarnWeight: "aran",
    hookSize: "5.5 mm (I-9)",
    thumbnailUrl: projectImage.granny,
    tags: ["blanket", "granny square", "beginner", "home decor"],
    downloads: 2103,
    rating: 4.7,
    ratingCount: 445,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Classic Granny Square Throw",
        description: "Timeless granny square blanket with modern colors.",
      },
      {
        language: "es",
        languageLabel: "Español",
        title: "Manta Clásica de Granny Square",
        description: "Manta atemporal con paleta de colores moderna.",
      },
      {
        language: "ja",
        languageLabel: "日本語",
        title: "クラシックグラニースクエアブランケット",
        description: "モダンな配色の定番グラニースクエアブランケット。",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mp-cozy-cardigan",
    designerId: "designer-james",
    designerName: "James Okonkwo",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-5.svg",
    title: "Weekend Cozy Cardigan",
    description:
      "A relaxed-fit cardigan with ribbed cuffs and patch pockets. Sized XS–3XL with diagram.",
    aiDescription:
      "Your new weekend uniform. This top-down cardigan features raglan shaping, deep pockets, and clear sizing notes for a flattering relaxed fit across six sizes.",
    previewText:
      "Top-down raglan · 6 sizes · 6.0 mm hook · DK weight · ~12 hours",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-cozy-cardigan"],
    priceCents: 1299,
    skillLevel: "advanced",
    projectType: "garment",
    yarnWeight: "dk",
    hookSize: "6.0 mm (J-10)",
    thumbnailUrl: projectImage.sweater,
    tags: ["cardigan", "garment", "sizing", "winter"],
    downloads: 634,
    rating: 4.9,
    ratingCount: 156,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Weekend Cozy Cardigan",
        description: "Relaxed-fit cardigan with ribbed cuffs and pockets.",
      },
      {
        language: "fr",
        languageLabel: "Français",
        title: "Cardigan Cosy du Week-end",
        description: "Cardigan ample avec poignets côtelés et poches.",
      },
      {
        language: "ko",
        languageLabel: "한국어",
        title: "주말 코지 가디건",
        description: "릴랙스 핏 가디건, 리브 커프스와 포켓 포함.",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mp-dino-buddy",
    designerId: "designer-maya",
    designerName: "Maya Chen",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-1.svg",
    title: "Tiny T-Rex Buddy",
    description:
      "An adorable mini dinosaur with poseable tail. Uses less than one skein of yarn.",
    aiDescription:
      "Small but mighty — this pocket-sized T-Rex is a quick make with big personality. Perfect stash buster with optional wire tail for posing.",
    previewText: "Mini amigurumi · 22 rounds · 3.5 mm hook · ~2 hours · Stash buster",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-dino-buddy"],
    priceCents: 399,
    skillLevel: "beginner",
    projectType: "amigurumi",
    yarnWeight: "worsted",
    hookSize: "3.5 mm (E-4)",
    thumbnailUrl: projectImage.dino,
    tags: ["dinosaur", "mini", "kids", "quick make"],
    downloads: 1567,
    rating: 4.8,
    ratingCount: 389,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Tiny T-Rex Buddy",
        description: "Adorable mini dinosaur with poseable tail.",
      },
      {
        language: "es",
        languageLabel: "Español",
        title: "Mini T-Rex Amigo",
        description: "Adorable mini dinosaurio con cola posable.",
      },
      {
        language: "it",
        languageLabel: "Italiano",
        title: "Piccolo Amico T-Rex",
        description: "Adorabile mini dinosauro con coda posabile.",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mp-frog-prince",
    designerId: "designer-luna",
    designerName: "Luna Park",
    designerAvatarUrl: "/assets/stitch/avatars/svg/avatar-6.svg",
    title: "Frog Prince Amigurumi",
    description:
      "A whimsical frog with a removable golden crown. Crown pattern included as bonus.",
    aiDescription:
      "Once upon a stitch — this frog prince comes with a detachable crochet crown for fairytale play. Great for nursery decor or storytime props.",
    previewText: "Amigurumi + crown bonus · 28 rounds · 4.0 mm hook · ~5 hours",
    patternContent: MARKETPLACE_PATTERN_CONTENT["mp-frog-prince"],
    priceCents: 699,
    skillLevel: "intermediate",
    projectType: "amigurumi",
    yarnWeight: "worsted",
    hookSize: "4.0 mm (G-6)",
    thumbnailUrl: projectImage.frog,
    tags: ["frog", "fairytale", "crown", "gift"],
    downloads: 978,
    rating: 4.9,
    ratingCount: 267,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Frog Prince Amigurumi",
        description: "Whimsical frog with removable golden crown.",
      },
      {
        language: "de",
        languageLabel: "Deutsch",
        title: "Froschkönig Amigurumi",
        description: "Verspielter Frosch mit abnehmbarer goldenen Krone.",
      },
      {
        language: "fr",
        languageLabel: "Français",
        title: "Prince Grenouille Amigurumi",
        description: "Grenouille fantaisiste avec couronne dorée amovible.",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: FEATURED_MARKETPLACE_LISTING_ID,
    designerId: "designer-ecoto",
    designerName: "Ecoto",
    title: "Cozy Granny Square Hoodie Crochet Pattern",
    description:
      "Women's size small boho granny square pullover hoodie with hood, drawstring, and ribbed hem.",
    aiDescription:
      "Handmade granny square construction meets modern comfort. This relaxed women's hoodie features a cozy hood with adjustable drawstring, ribbed cuffs and hem, and a coordinated six-color palette — perfect for intermediate makers who love join-as-you-go garment projects.",
    previewText:
      "64 granny squares · Intermediate · 5.0 mm hook · Worsted weight · Size small · Hood + ribbing",
    patternContent: MARKETPLACE_PATTERN_CONTENT[FEATURED_MARKETPLACE_LISTING_ID],
    priceCents: 1499,
    skillLevel: "intermediate",
    projectType: "garment",
    yarnWeight: "worsted",
    hookSize: "5.0 mm (H/8)",
    thumbnailUrl: learnImage.grannySquareHoodie,
    tags: ["hoodie", "granny square", "garment", "boho", "intermediate"],
    downloads: 847,
    rating: 4.8,
    ratingCount: 214,
    duplicateScore: 0,
    duplicateOfId: null,
    languages: [
      {
        language: "en",
        languageLabel: "English",
        title: "Cozy Granny Square Hoodie Crochet Pattern",
        description: "Relaxed women's granny square hoodie with hood and ribbed details.",
      },
      {
        language: "es",
        languageLabel: "Español",
        title: "Patrón de Sudadera con Capucha de Cuadros de la Abuela",
        description: "Sudadera relajada de cuadros de la abuela con capucha y ribetes.",
      },
      {
        language: "fr",
        languageLabel: "Français",
        title: "Modèle de Sweat à Capuche Granny Square",
        description: "Sweat ample en granny squares avec capuche et bordures côtelées.",
      },
      {
        language: "de",
        languageLabel: "Deutsch",
        title: "Gemütlicher Granny-Square-Hoodie",
        description: "Entspannter Granny-Square-Hoodie mit Kapuze und Rippenbündchen.",
      },
      {
        language: "ja",
        languageLabel: "日本語",
        title: "コージーグランニースクエアフーディ",
        description: "フード付きのリラックスフィットグラニースクエアフーディ。",
      },
    ],
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
];
