import { projectImage, scanImage } from "@/lib/project-images";
import type { SocialGroup, SocialMaker, SocialPost } from "@/lib/schemas/social";

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

export const SOCIAL_SEED_MAKERS: SocialMaker[] = [
  {
    id: "maker-maya",
    displayName: "Maya Chen",
    handle: "@mayastitches",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-1.svg",
    bio: "Amigurumi designer · Dog mom · Pattern tester for 12 indie designers",
    skillLevel: "advanced",
    projectCount: 47,
    followerCount: 2840,
    specialties: ["amigurumi", "colorwork", "design"],
    isFollowing: true,
  },
  {
    id: "maker-rosa",
    displayName: "Rosa Martinez",
    handle: "@rosayarns",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-2.svg",
    bio: "Market bags & home decor · Teaching beginners since 2019",
    skillLevel: "intermediate",
    projectCount: 31,
    followerCount: 1520,
    specialties: ["bags", "home decor", "teaching"],
    isFollowing: false,
  },
  {
    id: "maker-elena",
    displayName: "Elena Wright",
    handle: "@elena_hooks",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-4.svg",
    bio: "Granny squares forever · Blanket queen · Yarn swap host",
    skillLevel: "intermediate",
    projectCount: 62,
    followerCount: 3105,
    specialties: ["blankets", "granny squares", "community"],
    isFollowing: true,
  },
  {
    id: "maker-james",
    displayName: "James Okonkwo",
    handle: "@jamesknits",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-5.svg",
    bio: "Garment crochet · Size-inclusive patterns · DK weight enthusiast",
    skillLevel: "advanced",
    projectCount: 28,
    followerCount: 987,
    specialties: ["garments", "sizing", "raglan"],
    isFollowing: false,
  },
  {
    id: "maker-luna",
    displayName: "Luna Park",
    handle: "@lunacrochet",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-6.svg",
    bio: "Fairytale amigurumi · Slow fashion · Etsy shop owner",
    skillLevel: "intermediate",
    projectCount: 39,
    followerCount: 4210,
    specialties: ["amigurumi", "fairytale", "Etsy"],
    isFollowing: false,
  },
  {
    id: "maker-sam",
    displayName: "Sam Rivera",
    handle: "@samhooks",
    avatarUrl: "/assets/stitch/avatars/svg/avatar-3.svg",
    bio: "Beginner-friendly patterns · Weekend maker · Coffee & crochet",
    skillLevel: "beginner",
    projectCount: 14,
    followerCount: 456,
    specialties: ["beginner", "quick makes", "stash busting"],
    isFollowing: false,
  },
];

export const SOCIAL_SEED_GROUPS: SocialGroup[] = [
  {
    id: "group-amigurumi",
    name: "Amigurumi Makers United",
    description: "Share WIPs, get help with shaping, and celebrate finished plushies.",
    category: "Amigurumi",
    memberCount: 8420,
    imageUrl: projectImage.dino,
    isJoined: true,
  },
  {
    id: "group-beginners",
    name: "Crochet Beginners Circle",
    description: "No question too small. Friendly space for your first projects.",
    category: "Learning",
    memberCount: 12400,
    imageUrl: projectImage.granny,
    isJoined: true,
  },
  {
    id: "group-garments",
    name: "Hooked on Garments",
    description: "Cardigans, sweaters, and fit questions. Size-inclusive discussions.",
    category: "Garments",
    memberCount: 3680,
    imageUrl: projectImage.sweater,
    isJoined: false,
  },
  {
    id: "group-stash",
    name: "Stash Busters Anonymous",
    description: "Turn leftover skeins into magic. Weekly challenge threads.",
    category: "Challenges",
    memberCount: 5910,
    imageUrl: projectImage.sunflower,
    isJoined: false,
  },
  {
    id: "group-market",
    name: "Market Bag Makers",
    description: "Totes, farmers market bags, and sturdy construction tips.",
    category: "Projects",
    memberCount: 2150,
    imageUrl: projectImage.sunflower,
    isJoined: false,
  },
  {
    id: "group-vision",
    name: "Stitch Vision Community",
    description: "Share scan results, mistake fixes, and camera tips.",
    category: "Tools",
    memberCount: 1890,
    imageUrl: scanImage.dachshund,
    isJoined: false,
  },
];

export const SOCIAL_SEED_POSTS: SocialPost[] = [
  {
    id: "post-1",
    userId: "maker-maya",
    userName: "Maya Chen",
    userHandle: "@mayastitches",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-1.svg",
    content:
      "Finally attached the ears on this dachshund! The body shaping took three tries but I'm so happy with how floppy they turned out. 🐕",
    imageUrl: projectImage.dachshund,
    projectTitle: "Dachshund Plushie",
    likes: ["demo-user-emma", "maker-elena", "maker-luna"],
    comments: [
      {
        id: "c-1",
        userId: "maker-elena",
        userName: "Elena Wright",
        userAvatarUrl: "/assets/stitch/avatars/svg/avatar-4.svg",
        content: "Those ears are perfect! What hook size did you use?",
        createdAt: daysAgo(0.5),
      },
      {
        id: "c-2",
        userId: "maker-maya",
        userName: "Maya Chen",
        userAvatarUrl: "/assets/stitch/avatars/svg/avatar-1.svg",
        content: "4.0 mm with Bernat Velvet — holds shape beautifully!",
        createdAt: daysAgo(0.4),
      },
    ],
    createdAt: daysAgo(1),
  },
  {
    id: "post-2",
    userId: "maker-rosa",
    userName: "Rosa Martinez",
    userHandle: "@rosayarns",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-2.svg",
    content:
      "Sunflower panel done! 🌻 Now onto the bag body. Who else is making market totes this season?",
    imageUrl: projectImage.sunflower,
    projectTitle: "Sunflower Market Tote",
    likes: ["demo-user-emma", "maker-sam"],
    comments: [
      {
        id: "c-3",
        userId: "maker-sam",
        userName: "Sam Rivera",
        userAvatarUrl: "/assets/stitch/avatars/svg/avatar-3.svg",
        content: "This is on my list! Saving your post for motivation.",
        createdAt: daysAgo(1.5),
      },
    ],
    createdAt: daysAgo(2),
  },
  {
    id: "post-3",
    userId: "maker-elena",
    userName: "Elena Wright",
    userHandle: "@elena_hooks",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-4.svg",
    content:
      "Square 14 of 20 for my granny throw. Join-as-you-go is a game changer — barely any ends to weave! Blanket weather can't come soon enough.",
    imageUrl: projectImage.granny,
    projectTitle: "Granny Square Throw",
    likes: ["maker-maya", "maker-james", "demo-user-emma", "maker-luna"],
    comments: [],
    createdAt: daysAgo(3),
  },
  {
    id: "post-4",
    userId: "maker-james",
    userName: "James Okonkwo",
    userHandle: "@jamesknits",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-5.svg",
    content:
      "Sleeve cap shaping tip: place markers at the raglan lines and count decreases every other row. Changed my garment game completely.",
    projectTitle: "Weekend Cozy Cardigan",
    likes: ["maker-elena"],
    comments: [
      {
        id: "c-4",
        userId: "demo-user-emma",
        userName: "Emma",
        userAvatarUrl: "/assets/stitch/avatars/svg/avatar-3.svg",
        content: "Bookmarking this — about to start my first cardigan!",
        createdAt: daysAgo(4),
      },
    ],
    createdAt: daysAgo(5),
  },
  {
    id: "post-5",
    userId: "maker-luna",
    userName: "Luna Park",
    userHandle: "@lunacrochet",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-6.svg",
    content:
      "Frog prince got his crown today 👑 Pattern drops in the Marketplace tomorrow!",
    imageUrl: projectImage.frog,
    projectTitle: "Frog Prince Amigurumi",
    patternRef: "mp-frog-prince",
    likes: ["maker-maya", "maker-rosa", "maker-sam", "demo-user-emma"],
    comments: [
      {
        id: "c-5",
        userId: "maker-rosa",
        userName: "Rosa Martinez",
        userAvatarUrl: "/assets/stitch/avatars/svg/avatar-2.svg",
        content: "The crown detail is everything! Can't wait.",
        createdAt: daysAgo(0.8),
      },
    ],
    createdAt: daysAgo(0.9),
  },
  {
    id: "post-6",
    userId: "demo-user-emma",
    userName: "Emma",
    userHandle: "@emma_crochet",
    userAvatarUrl: "/assets/stitch/avatars/svg/avatar-3.svg",
    content:
      "Used Stitch Vision on my dachshund WIP — it caught a missed increase on row 22 before I went too far. Lifesaver! 🧶",
    imageUrl: scanImage.dachshund,
    projectTitle: "Dachshund Plushie",
    likes: ["maker-maya"],
    comments: [],
    createdAt: daysAgo(0.2),
  },
];
