import { NextRequest } from "next/server";
import { jsPDF } from "jspdf";
import {
  jsonError,
  jsonSuccess,
  methodNotAllowed,
  parseJsonBody,
  zodErrorResponse,
} from "@/lib/api-utils";
import { generatedPatternSchema } from "@/lib/schemas/pattern";
import { rateLimit } from "@/lib/rate-limit";
import { ZodError } from "zod";

export async function POST(request: NextRequest) {
  const limit = rateLimit(request, { limit: 10, windowMs: 60_000 });
  if (!limit.success) {
    return jsonError("Rate limit exceeded. Try again shortly.", 429);
  }

  try {
    const body = await parseJsonBody(request);
    const pattern = generatedPatternSchema.parse(body);

    const doc = new jsPDF({ unit: "pt", format: "letter" });
    const margin = 48;
    let y = margin;
    const lineHeight = 14;
    const pageHeight = doc.internal.pageSize.getHeight();

    const addLine = (text: string, size = 11, bold = false) => {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      const lines = doc.splitTextToSize(text, 516);
      doc.text(lines, margin, y);
      y += lines.length * lineHeight + 4;
    };

    addLine(pattern.title, 18, true);
    if (pattern.description) addLine(pattern.description);
    addLine(
      `Skill: ${pattern.skillLevel} · Terminology: ${pattern.terminology.toUpperCase()} · Hook: ${pattern.materials.hookSize}`,
      10,
    );

    addLine("Materials", 14, true);
    for (const yarn of pattern.materials.yarns) {
      addLine(
        `• ${yarn.colorName} — ${yarn.weight}${yarn.yardage ? `, ${yarn.yardage} yds` : ""}`,
      );
    }
    if (pattern.materials.notions?.length) {
      addLine(`Notions: ${pattern.materials.notions.join(", ")}`);
    }

    addLine("Gauge", 14, true);
    addLine(
      `${pattern.gauge.stitches} sts × ${pattern.gauge.rows} rows = ${pattern.gauge.measurement}`,
    );

    addLine("Abbreviations", 14, true);
    addLine(
      Object.entries(pattern.abbreviations)
        .map(([k, v]) => `${k} = ${v}`)
        .join(" · "),
      10,
    );

    for (const section of pattern.sections) {
      addLine(section.name, 14, true);
      if (section.instructions) addLine(section.instructions, 10);
      for (const row of section.rows) {
        const count =
          row.stitchCount != null ? ` (${row.stitchCount} sts)` : "";
        addLine(`R${row.rowNumber}: ${row.instruction}${count}`, 10);
      }
    }

    if (pattern.assemblyInstructions?.length) {
      addLine("Assembly", 14, true);
      for (const step of pattern.assemblyInstructions) {
        addLine(`• ${step}`);
      }
    }

    if (pattern.finishingInstructions?.length) {
      addLine("Finishing", 14, true);
      for (const step of pattern.finishingInstructions) {
        addLine(`• ${step}`);
      }
    }

    addLine("— Generated by Stitch by Nuvio", 9);

    const pdfBase64 = doc.output("datauristring");

    return jsonSuccess(
      {
        filename: `${pattern.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`,
        mimeType: "application/pdf",
        dataUrl: pdfBase64,
        pageCount: doc.getNumberOfPages(),
      },
      limit,
    );
  } catch (error) {
    if (error instanceof ZodError) return zodErrorResponse(error);
    if (error instanceof Error && error.message === "Invalid JSON body") {
      return jsonError("Invalid JSON body", 400);
    }
    console.error("[api/export/pattern-pdf]", error);
    return jsonError("Failed to export pattern PDF", 500);
  }
}

export function GET() {
  return methodNotAllowed();
}
